# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc26bcddbb8a26edfb206b1952f0e469c49b61bee326803835fd0fefb4805c48b9831af93316dd9afffa3ba7f9252c69bcfb7e1071d4eac9970fa7a5ae9cf596

test:
  secret_key_base: 5c10eb2196777f8416e9df7d5fa612d3bb8d180b153538e74b7400047a5a8aae9f76003252361be92b8b0b40cfd641de270aadb9d23bfb5f653e0bea4f5ea5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
