# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b29ae0fb8c287b9c9b8a884c99b1f64f6b6fddbdda44d4a5b707d79f6dd765b7072d3a42f5e54383d1d4dc388c3db4a4b133a8d9cd9c04b2fb9dabcc17c33960

test:
  secret_key_base: 3f4963868c552a14575fa323e9d8ace1345981e1dde0243d72197793cf083bab8a69475a534b049c3af7c21a197e3c923b2c973313f6bbf46b3ba5981d743219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
